apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress
spec:
  # inputs:
  #   params:
  #     - name: URL
  #       description: The base url which you want to test
  steps:
    - name: E2E Test
      image: cypress/included:4.6.0
      workingDir: "/workspace"
      command: ["/bin/bash"]
      args:
        - -c
        - |
          echo 'Testing...'
          npm run e2e
      env:
        - name: "CYPRESS_HOST"
          value: "http://productpage"
